name: Desktop App Build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pyinstaller==6.8.0

      - name: Build backend binary
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            pyinstaller -F -n backend-server backend/entry.py
            mkdir -p backend
            cp dist/backend-server.exe backend/
          else
            pyinstaller -F -n backend-server backend/entry.py
            mkdir -p backend
            cp dist/backend-server backend/
          fi

      - name: Install JS dependencies
        run: |
          npm install
          npm run install-frontend

      - name: Build frontend
        run: npm run build

      - name: Package Electron app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx electron-builder --publish never

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: desktop-${{ matrix.os }}
          path: |
            dist/**/*
          if-no-files-found: warn

